language: python
python:
        - "2.7"
        - "3.5"
cache: pip
install:
        - pip install -r requirements.txt
before_script: cd gdrive_sync/tests
script:
        - python -m unittest discover -v
